# Generated by Django 2.2.1 on 2019-11-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_for', models.CharField(choices=[('APHG', 'AP Human Geo'), ('GEO', 'Geometry'), ('Spanish 1', 'Spanish 1'), ('English 1', 'English 1'), ('French 1', 'French 1'), ('Algebra 1', 'Algebra 1')], max_length=15)),
                ('assignment_name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('approval', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('approve_answers', 'Can approve answers'), ('create_answers', 'Can create answers')],
            },
        ),
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('changes', models.TextField()),
            ],
        ),
    ]
